# Site settings
title: The Dungeons
### description: >-
###   Some stuff.
url: "https://stefaanc.github.io"                                            # <<<<<
###url: "localhost:4000"                                                           # >>>>>
baseurl: "/"

author: Stefaan Coussement
email: stefaan.coussement@gmail.com
linkedin_username: stefaan-coussement
github_username:  stefaanc

header_pages:
  - index.md
  - bookmarks.md
  - projects.md
  - tools.md

###show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jemoji                                                                   # <<<<<
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
